//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conciertos
    {
        public int id_Concierto { get; set; }
        public int id_Banda { get; set; }
        public int id_Genero { get; set; }
        public System.DateTime fechaHora_Concierto { get; set; }
        public int id_Pais { get; set; }
        public string direccion { get; set; }
        public string poster_Url { get; set; }
    
        public virtual Bandas Bandas { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
